### ISSUE TITLE
ExternalAttribute

### ISSUE THREAD

**Issue by MichelleCnatalio** [waynegm/OpendTect-Plugins#43]

**Comment by MichelleCnatalio** [comment]
Hi! I'm trying to run the the ExternalAttribute with OpendTect 6.4.0  on W10.
When I start the program, I don't find the plugins.

**Comment by waynegm** [comment]
Is it just the External Attribute plugin or all my plugins? Do you see the "AVO Attribute (UI)" when you invoke the "Utilities | Installation | Plugins" menu? Like this:
![plugin_list](https://user-images.githubusercontent.com/3080502/60748866-79b0ef80-9fd5-11e9-85a8-c8ea7ab21592.png)

If not then you need to move/copy my plugin files to a location where OpendTect can find them. The available options are explained in [the documentation](http://waynegm.github.io/OpendTect-Plugin-Docs/installation/installation.html). 

As a further check if you press the "Load a Plugin" button on the dialog above the file dialog should contain "AVOAttrib.dll, AVOPolarAttrib.dll, ExternalAttrib.dll etc". If "ExternalAttrib.dll" is not listed  scroll to the bottom of the list and let me know if it appears below the "-Not loaded" line.

**Comment by MichelleCnatalio** [comment]
I explainned wrong. these external attributes I can load, the
ExternalAttributes developed in Python are with those that I have problem,
I followed this instructions
http://waynegm.github.io/OpendTect-Plugin-Docs/plugins/ExternalAttrib.html#issues,
when I start OpendTect, the plugin is not the list.

**Comment by MichelleCnatalio** [comment]
I have made it, a small mistake, thanks!
